travis:
  secure:
    BINSTAR_TOKEN: TdF+g104CgvkIzUa64hCSgNFymCb5iW4/Xz5maysBQWuGB2jYzpRC8D5HxtbwtLhG3W8Ly3UL7o7lmp3YC4GI9WZridVbYpQP3ViIG2foHNnxgt1APz3lH1X0DeI3CcNBJXV6/VVIwK6BkBbHeaGrlhUTqVeAlCpwcrgB082YlG468Tv6O6yEr5ZbKthiGbytD3kWD7p5LozDVDXhEdFAa8gU3KeUz7+pGY8pzek9zMWQqcfGVQYBH3PK43oFpGeDf2dP9Wo2Q5U0aOZ3fsC51uoFqVCFgNdbYrxeCy5tiCMrmy2hPw40Lr+Bdun8DeVMIdVazSC7U095cr+KSvGN61JLlIHTmkUR0uVhCJYbziSBCLoEZ+3HPH8lKJAZk+kce24RqYncrBDnsKwn7SYkeynEq3hBN5TZ7Tg55oQ6UJIW/huFPNGuMu9c9MHC+vKJg5MToXuH2FZDbKw6JJ2AiWWGKXFxrf+ltTgf8f4NeVoNPuCftCEN0g+OjZ4uTiGWNjQMiyRFCqjcztANdNS95B5wIlVVrQmf5JMxAm/MgeaNu/pr9ZSHI6ylN5wFWRn8RQuotYP8OLECdznA7xbQFnwGQ3o05bTTLEGYxtS+RxmdFHMb4HXhGmyi8Vn4ATZ29w2z04XqxEHC9PiAb1QnZK9+4Fd8k/dNPBQVR2E4wg=
conda_forge_output_validation: true
bot:
  automerge: true
